/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      sans: ["Open Sans", "sans-serif"],
      secondary: ["DM Serif Display", "serif"],
    },
    colors: {
      white: "#fff",
      "light-background": "hsl(0, 0%, 96%)",
      "light-on-background": "hsl(0, 3%, 13%)",
      "light-on-background-variant": "hsl(20, 3%, 19%)",
      "light-primary": "hsl(11, 87%, 59%)",
      "light-primary-hover": "hsl(11, 60%, 50%)",
      "light-primary-container": "hsl(14, 57%, 95%)",
      "light-error": "hsl(1, 73%, 42%)",
      "light-active-indicator": "hsl(12, 58%, 88%)",
      "light-image-background": "hsl(0, 0%, 70%)",
      "light-badge-btn": "hsl(30, 58%, 88%)",
      "light-on-badge-btn": "hsl(24, 7%, 14%)",
      "light-outline": "hsl(10, 19%, 88%)",
      "light-input-outline": "hsl(7, 7%, 73%)",
      "light-input-outline-hover": "hsl(9, 3%, 52%)",
      "light-alpha-10": "hsla(0, 0%, 0%, 0.1)",
      "light-alpha-20": "hsla(0, 0%, 0%, 0.2)",

      "dark-background": " hsl(0, 0%, 10%)",
      "dark-on-background": " hsl(11, 3%, 87%)",
      "dark-on-background-variant": " hsl(11, 3%, 81%)",
      "dark-primary": " hsl(11, 87%, 64%)",
      "dark-primary-hover": " hsl(11, 51%, 51%)",
      "dark-primary-container": " hsl(15, 3%, 15%)",
      "dark-error": " hsl(1, 69%, 59%)",
      "dark-active-indicator": " hsl(15, 25%, 22%)",
      "dark-image-background": " hsl(0, 0%, 30%)",
      "dark-badge-btn": " hsl(30, 28%, 13%)",
      "dark-on-badge-btn": " hsl(30, 8%, 86%)",
      "dark-outline": " hsl(11, 3%, 20%)",
      "dark-input-outline": " hsl(11, 3%, 29%)",
      "dark-input-outline-hover": " hsl(0, 4%, 58%)",
      "dark-alpha-10": " hsla(0, 0%, 100%, 0.1)",
      "dark-alpha-20": " hsla(0, 0%, 100%, 0.2)",
    },
  },
};
